### ISSUE TITLE
请问会出现绘制答案无法被小猿识别的情况怎么办

### ISSUE THREAD

**Issue by TilapiaLog** [extrant/KouSuanOCR#1]
请问会出现绘制答案无法被小猿识别的情况怎么办

**Comment by extrant** [comment]
OCR还是MITM，可能是画太快了。手动调整time.sleep(0.3)这类极短的延时增加到例如time.sleep(0.4)。以及无法识别的情况是脚本一直在绘制还是说一直是画错了。

**Comment by hemo528** [comment]
> 请问会出现绘制答案无法被小猿识别的情况怎么办

不能把模拟器放后台，要放前台，放后台就画不上去了
