### ISSUE TITLE
代码中大于号的坐标错误

### ISSUE THREAD

**Issue by chun1125** [extrant/KouSuanOCR#2]
**原代码**
        if answer == ">":
            print(f"题目 {idx + 1}: 执行 '>' 滑动操作")
            os.system("adb shell input swipe 600 900 1000 800 0")
            os.system("adb shell input swipe 600 800 1000 900 0")
![image](https://github.com/user-attachments/assets/145adbdf-9649-4851-abe4-3683e4d7674b)
**执行后为一个×号，不是大于号**
建议修改为
        if answer == ">":
            print(f"题目 {idx + 1}: 执行 '>' 滑动操作")
            os.system("adb shell input swipe 600 800 1000 900 0")
            os.system("adb shell input swipe 1000 900 600 1000 0")

**Comment by extrant** [comment]
我当初看能识别就直接用了，我改一下。
