### ISSUE TITLE
想问一下 抓包.bat 闪退

### ISSUE THREAD

**Issue by david-xu1021** [extrant/KouSuanOCR#5]
您好 想问一下 连接好了adb 但是运行抓包bat之后返回解码格式error

匹配到目标请求: https://xyks.yuanfudao.com/leo-game-pk/android/math/pk/match/v2?pointId=69&_productId=611&platform=android32&version=3.93.3&vendor=baidu&av=5&sign=03ad88c784d94ba40c4b5ed106b99c27&deviceCategory=pad
[20:06:23.108] Addon error: UnicodeDecodeError when decoding b'\xcb\xb2 with 'utf-8':

**Comment by extrant** [comment]
编码错误，print一下json的内容。

**Comment by extrant** [comment]
> 您好 想问一下 连接好了adb 但是运行抓包bat之后返回解码格式error
> 
> 匹配到目标请求: https://xyks.yuanfudao.com/leo-game-pk/android/math/pk/match/v2?pointId=69&_productId=611&platform=android32&version=3.93.3&vendor=baidu&av=5&sign=03ad88c784d94ba40c4b5ed106b99c27&deviceCategory=pad [20:06:23.108] Addon error: UnicodeDecodeError when decoding b'\xcb\xb2 with 'utf-8':

网络包被加密了
